# trigger:
#  branches:
#    include:
#        - main
#  paths:
#   include:
#       - app/Resources/*


# schedules:
# - cron: "0 3 * * 1-5"
#  displayName: iOS Daily Build
#  branches:
#    include: [ main ] 
#  always: false   

pool:
  vmImage: 'macOS-12'

# variables:
#  MAINMOB: $(System.DefaultWorkingDirectory)
#  buildPatchNumber: $[counter(variables['build.reason'], 0)]

steps:

- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSource: 'spec'
    versionSpec: '14.21.3'

- task: Bash@3
  displayName: 'Set Java version'
  inputs:
    targetType: 'inline'
    script: |
      # Set the right java version:
      echo "JAVA_HOME_17_X64: $JAVA_HOME_17_X64"
      export JAVA_HOME=$JAVA_HOME_17_X64
      echo "JAVA_HOME: $JAVA_HOME"
      java -version
      #brew install ccache

- task: Bash@3
  displayName: 'Java check'
  inputs:
    targetType: 'inline'
    script: |
      java -version

- task: Bash@3
  displayName: 'Brew ccache'
  inputs:
    targetType: 'inline'
    script: |

      # Install ccache with brew
      # brew is preinstalled
      brew install ccache


- task: Bash@3
  displayName: 'Build Titanium'
  inputs:
    targetType: 'inline'
    script: |

      cd $(System.DefaultWorkingDirectory)
      # Install Titanium CI dependencies (node_modules)
      npm ci
      # Build the Titanium framework, using a clean build:
      npm run cleanbuild

# - task: PublishPipelineArtifact@1
#   displayName: 'Publish zip file as an artifact'
#   inputs:
#     targetPath: '$(System.DefaultWorkingDirectory)/dist/mobilesdk-11.1.1.zip'
#     artifact: 'mobilesdk-11.1.1.zip'
#     publishLocation: 'pipeline'

# - task: UniversalPackages@0
#   inputs:
#     command: 'publish'
#     publishDirectory: '$(Build.ArtifactStagingDirectory)'
#     feedsToUsePublish: 'internal'
#     vstsFeedPublish: '159a4be2-6a10-4946-a199-ceba2c906e34/91173f7c-449b-4969-b0f6-8b71905945d5'
#     vstsFeedPackagePublish: 'vxf_tf_12.1.1.RC'
#     versionOption: 'custom'
#     versionPublish: '12.1.1.GA'
#     packagePublishDescription: 'Titanium Framework 12.1.1.RC'


